⁹const CATALOG_DATA = [
 {
  "id": 1,
  "category": "Spannungsversorgungskabel - BZ Standard - 3.HZ",
  "name": "Basiszähler zu SMGw  33 cm",
  "hersteller": "MC-Technologies",
  "materialnummer": "10297241",
  "materialschluessel": "001-221001",
  "artikeltyp": "Z00259",
  "bestellnummer": "BZ0023",
  "typbezeichnung": "105033A2 Spannungs-versorgungskabel 33 cm",
  "beschreibung": "Kabel zum Anschluss von SMGw und wahlweise Steuerbox im 3.HZ-Basiszähler.",
  "statusList": [
   "lager-egs",
   "lager-westnetz"
  ],
  "image": "images/img_1.jpg"
 },
 {
  "id": 2,
  "category": "Spannungsversorgungskabel - BZ Standard - 3.HZ",
  "name": "Basiszähler zu SMGw/Steuerbox 33 + 20 cm",
  "hersteller": "",
  "materialnummer": "10297232",
  "materialschluessel": "001-221002",
  "artikeltyp": "Z00260",
  "bestellnummer": "BZ0032",
  "typbezeichnung": "105034A1 Spannungs- versorgungskabel Y 33 + 20 cm",
  "beschreibung": "",
  "statusList": [
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 3,
  "category": "Spannungsversorgungskabel - BZ Standard - 3.HZ",
  "name": "Basiszähler zu SMGw 33 cm",
  "hersteller": "Sicatron",
  "materialnummer": "10297241",
  "materialschluessel": "001-221001",
  "artikeltyp": "Z00263",
  "bestellnummer": "BZ0023",
  "typbezeichnung": "3204151//K-\nStandard 230 V",
  "beschreibung": "",
  "statusList": [
   "lager-egs",
   "lager-westnetz"
  ],
  "image": "images/img_2.jpg"
 },
 {
  "id": 4,
  "category": "Spannungsversorgungskabel - BZ Standard - 3.HZ",
  "name": "Basiszähler zu SMGw/Steuerbox 33 + 20 cm",
  "hersteller": "",
  "materialnummer": "10297232",
  "materialschluessel": "001-221002",
  "artikeltyp": "Z00264",
  "bestellnummer": "BZ0032",
  "typbezeichnung": "3204152//K-Y \n230V_3.HZ",
  "beschreibung": "",
  "statusList": [
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 5,
  "category": "Spannungsversorgungskabel - BZ Standard - 3.HZ",
  "name": "Basiszähler zu SMGw 33 cm",
  "hersteller": "PTR-Hartmann",
  "materialnummer": "10297241",
  "materialschluessel": "001-221001",
  "artikeltyp": "Z00261",
  "bestellnummer": "BZ0023",
  "typbezeichnung": "Netzkabel Standard \u000b230 V 33 cm",
  "beschreibung": "",
  "statusList": [
   "lager-egs",
   "lager-westnetz"
  ],
  "image": "images/img_3.jpg"
 },
 {
  "id": 6,
  "category": "Spannungsversorgungskabel - BZ Standard - 3.HZ",
  "name": "Basiszähler zu SMGw/Steuerbox 33 + 20 cm",
  "hersteller": "",
  "materialnummer": "10297232",
  "materialschluessel": "001-221002",
  "artikeltyp": "Z00262",
  "bestellnummer": "BZ0032",
  "typbezeichnung": "Netzkabel Standard\u000b230 V 33 + 20 cm",
  "beschreibung": "",
  "statusList": [
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 7,
  "category": "Kommunikation OKK",
  "name": "OKK - MS2020 - Iskra OKK eHZ 2020 (50 cm)",
  "hersteller": "EMH",
  "materialnummer": "10297046",
  "materialschluessel": "001-220001",
  "artikeltyp": "Z00208",
  "bestellnummer": "",
  "typbezeichnung": "MS2020 OKK 50 cm",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 8,
  "category": "Kommunikation OKK",
  "name": "OKK - MS2020 - Iskra OKK eHZ 2020 (100 cm)",
  "hersteller": "",
  "materialnummer": "10297066",
  "materialschluessel": "001-220002",
  "artikeltyp": "Z00209",
  "bestellnummer": "",
  "typbezeichnung": "MS2020 OKK 100 cm",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 9,
  "category": "Kommunikation OKK",
  "name": "OKK - MS2020 - Iskra OKK eHZ 2020 (50 cm)",
  "hersteller": "Iskra",
  "materialnummer": "10297046",
  "materialschluessel": "001-220001",
  "artikeltyp": "Z00254",
  "bestellnummer": "BZ0016",
  "typbezeichnung": "MS2020 OKK 50 cm",
  "beschreibung": "",
  "statusList": [
   "lager-egs",
   "lager-westnetz"
  ],
  "image": null
 },
 {
  "id": 10,
  "category": "Kommunikation OKK",
  "name": "OKK - MS2020 - Iskra OKK eHZ 2020 (100 cm)",
  "hersteller": "",
  "materialnummer": "10297066",
  "materialschluessel": "001-220002",
  "artikeltyp": "Z00431",
  "bestellnummer": "BZ0022",
  "typbezeichnung": "MS2020 OKK 100 cm",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 11,
  "category": "Antennen - LTE-Antennen - Easy-Fix (ehemals Unterputz)",
  "name": "LTE Easy-Fix \n12Q-A015-AK-30 - 1,5 m",
  "hersteller": "A-Antennas",
  "materialnummer": "10295859",
  "materialschluessel": "001-210001",
  "artikeltyp": "Z00338",
  "bestellnummer": "",
  "typbezeichnung": "12Q-A015-AK-30",
  "beschreibung": "Ab 800 MHz, durch Z00356 abgelöst!",
  "statusList": [],
  "image": "images/img_4.jpg"
 },
 {
  "id": 12,
  "category": "Antennen - LTE-Antennen - Easy-Fix (ehemals Unterputz)",
  "name": "LTE Easy-Fix\n23N-A015-AK-30 - 1,5 m",
  "hersteller": "",
  "materialnummer": "10295859",
  "materialschluessel": "001-210001",
  "artikeltyp": "Z00356",
  "bestellnummer": "BZ0027",
  "typbezeichnung": "23N-A015-AK-30",
  "beschreibung": "Ab 700 MHz",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": "images/img_5.jpg"
 },
 {
  "id": 13,
  "category": "Antennen - LTE-Antennen - Easy-Fix (ehemals Unterputz)",
  "name": "LTE Easy-Fix\nLP-IN2825-1-5 - 1,5 m",
  "hersteller": "Panorama-Antennas",
  "materialnummer": "10295859",
  "materialschluessel": "001-210001",
  "artikeltyp": "Z00336",
  "bestellnummer": "BZ0027",
  "typbezeichnung": "LPWTC-7-27",
  "beschreibung": "Ab 700 MHz",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": "images/img_6.jpg"
 },
 {
  "id": 14,
  "category": "Antennen - LTE-Antennen - Easy-Fix (ehemals Unterputz)",
  "name": "LTE Easy-Fix - LP 701 Low Profile 2G/3G/4G Multiband (Fakra-D) - 1,5 m",
  "hersteller": "PCTel/Smarteq",
  "materialnummer": "10295859",
  "materialschluessel": "001-210001",
  "artikeltyp": "Z00293",
  "bestellnummer": "BZ0027",
  "typbezeichnung": "LP 701 Low Profile 2G/3G/4G",
  "beschreibung": "Feldtest noch offen!",
  "statusList": [],
  "image": "images/img_7.jpg"
 },
 {
  "id": 15,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "12Q-A015-AK-01\n1,5 m",
  "hersteller": "A-Antennas",
  "materialnummer": "10296636",
  "materialschluessel": "001-210002",
  "artikeltyp": "Z00314",
  "bestellnummer": "",
  "typbezeichnung": "12Q-A015-AK-01",
  "beschreibung": "Ab 800 MHz, durch Z00347 und Z00348 abgelöst!",
  "statusList": [],
  "image": "images/img_8.jpg"
 },
 {
  "id": 16,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "12Q-A030-AK-01\n3 m",
  "hersteller": "",
  "materialnummer": "10292148",
  "materialschluessel": "001-210003",
  "artikeltyp": "Z00303",
  "bestellnummer": "",
  "typbezeichnung": "12Q-A030-AK-01",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_8.jpg"
 },
 {
  "id": 17,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "23N-A015-AK-01\n1,5 m",
  "hersteller": "",
  "materialnummer": "10296636",
  "materialschluessel": "001-210002",
  "artikeltyp": "Z00347",
  "bestellnummer": "BZ0020",
  "typbezeichnung": "23N-A015-AK-01",
  "beschreibung": "Ab 700 MHz",
  "statusList": [],
  "image": "images/img_9.jpg"
 },
 {
  "id": 18,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "23N-A030-AK-01\n3 m",
  "hersteller": "",
  "materialnummer": "10292148",
  "materialschluessel": "001-210003",
  "artikeltyp": "Z00348",
  "bestellnummer": "BZ0019",
  "typbezeichnung": "23N-A030-AK-01",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz"
  ],
  "image": "images/img_9.jpg"
 },
 {
  "id": 19,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "LP-IN2640-1-5\n1,5 m",
  "hersteller": "Panorama-Antennas",
  "materialnummer": "10296636",
  "materialschluessel": "001-210002",
  "artikeltyp": "Z00326",
  "bestellnummer": "BZ0020",
  "typbezeichnung": "LP-IN2640-1-5",
  "beschreibung": "Ab 700 MHz",
  "statusList": [],
  "image": "images/img_10.jpg"
 },
 {
  "id": 20,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "LP-IN2640-3\n3 m",
  "hersteller": "",
  "materialnummer": "10292148",
  "materialschluessel": "001-210003",
  "artikeltyp": "Z00310",
  "bestellnummer": "BZ0019",
  "typbezeichnung": "LP-IN2640-3",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz"
  ],
  "image": "images/img_10.jpg"
 },
 {
  "id": 21,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "LP 701 Low Profile (Fakra-D) - 1,5 m",
  "hersteller": "PCTel/Smarteq",
  "materialnummer": "10296636",
  "materialschluessel": "001-210002",
  "artikeltyp": "Z00358",
  "bestellnummer": "BZ0020",
  "typbezeichnung": "LP 701 Low Profile 2G/3G/4G Multiband (Fakra-D) - 1,5 m",
  "beschreibung": "Feldtest noch offen!",
  "statusList": [],
  "image": "images/img_11.jpg"
 },
 {
  "id": 22,
  "category": "Antennen - LTE-Antennen - Standard",
  "name": "LP 701 Low Profile (Fakra-D) - 3 m",
  "hersteller": "",
  "materialnummer": "10292148",
  "materialschluessel": "001-210003",
  "artikeltyp": "Z00359",
  "bestellnummer": "BZ0019",
  "typbezeichnung": "LP 701 Low Profile 2G/3G/4G Multiband (Fakra-D) - 3 m",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_11.jpg"
 },
 {
  "id": 23,
  "category": "Antennen - LTE-Antennen - ZWT",
  "name": "LP 701 Low Profile (Fakra-D) - 0,5 m",
  "hersteller": "",
  "materialnummer": "10295860",
  "materialschluessel": "001-210015",
  "artikeltyp": "Z00321",
  "bestellnummer": "",
  "typbezeichnung": "LTE ZWT Antenne - LP 701 Low Profile 2G/3G/4G Multiband (Fakra-D) – 0,5 m",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_12.jpg"
 },
 {
  "id": 24,
  "category": "Antennen - LTE-Antennen - Premium (SMA)",
  "name": "LTE Premium Antenne - 23O-A030-AB-01 - Midpatch Flat Klebeantenne (SMA) - 3 m",
  "hersteller": "A-Antennas",
  "materialnummer": "10298802",
  "materialschluessel": "001-210208",
  "artikeltyp": "Z00382",
  "bestellnummer": "BZ0061",
  "typbezeichnung": "LTE Midpatch Flat\n23O-A030-AB-01",
  "beschreibung": "Nachfolger der Fakra-Variante",
  "statusList": [],
  "image": "images/img_13.jpg"
 },
 {
  "id": 25,
  "category": "Antennen - LTE-Antennen - Premium (SMA)",
  "name": "LTE Premium Antenne - LP 701 Low Profile 2G/3G/4G Multiband (SMA) - 3 m",
  "hersteller": "Smarteq",
  "materialnummer": "10298802",
  "materialschluessel": "001-210208",
  "artikeltyp": "Z00383",
  "bestellnummer": "",
  "typbezeichnung": "LP701",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_14.jpg"
 },
 {
  "id": 26,
  "category": "Antennen - LTE-Antennen - Premium (SMA)",
  "name": "LTE Premium Antenne - LP-IN2683-[VAR] (SMA) - 3 m",
  "hersteller": "Panorama-Antennas",
  "materialnummer": "10298802",
  "materialschluessel": "001-210208",
  "artikeltyp": "Z00384",
  "bestellnummer": "BZ0061",
  "typbezeichnung": "SiSo 4G/5G LOW PROFILE IOT ANT\nLP-IN2683-3",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_15.jpg"
 },
 {
  "id": 27,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "LTE Bracket Antenna (Fakra D) - 2,5 m",
  "hersteller": "A-Antennas",
  "materialnummer": "10295770",
  "materialschluessel": "001-210206",
  "artikeltyp": "Z00241",
  "bestellnummer": "BZ0037",
  "typbezeichnung": "LTE Bracket Antenna",
  "beschreibung": "Stabantenne",
  "statusList": [],
  "image": "images/img_16.jpg"
 },
 {
  "id": 28,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "LTE Bracket Antenna (Fakra D) - 5 m",
  "hersteller": "",
  "materialnummer": "10295861",
  "materialschluessel": "001-210207",
  "artikeltyp": "Z00242",
  "bestellnummer": "BZ0039",
  "typbezeichnung": "LTE Bracket Antenna",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_16.jpg"
 },
 {
  "id": 29,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "LTE Bracket Antenna (Fakra D) - 10 m",
  "hersteller": "",
  "materialnummer": "10295862",
  "materialschluessel": "001-210205",
  "artikeltyp": "Z00243",
  "bestellnummer": "BZ0041",
  "typbezeichnung": "LTE Bracket Antenna",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_16.jpg"
 },
 {
  "id": 30,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "LTE Bracket Antenna (SMA) - 2,5 m",
  "hersteller": "",
  "materialnummer": "10298803",
  "materialschluessel": "001-210209",
  "artikeltyp": "Z00395",
  "bestellnummer": "",
  "typbezeichnung": "LTE Bracket Antenna",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_16.jpg"
 },
 {
  "id": 31,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "LTE Bracket Antenna (SMA) - 5 m",
  "hersteller": "",
  "materialnummer": "10298804",
  "materialschluessel": "001-210210",
  "artikeltyp": "Z00396",
  "bestellnummer": "",
  "typbezeichnung": "LTE Bracket Antenna",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_16.jpg"
 },
 {
  "id": 32,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "LTE Bracket Antenna (SMA) - 10 m",
  "hersteller": "",
  "materialnummer": "10298805",
  "materialschluessel": "001-210211",
  "artikeltyp": "Z00397",
  "bestellnummer": "",
  "typbezeichnung": "LTE Bracket Antenna",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_16.jpg"
 },
 {
  "id": 33,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "B4-IN2642\n(Fakra D) - 2,5 m",
  "hersteller": "Panorama-Antennas",
  "materialnummer": "10295770",
  "materialschluessel": "001-210203",
  "artikeltyp": "Z00244",
  "bestellnummer": "BZ0037",
  "typbezeichnung": "B4-IN2642",
  "beschreibung": "Becherantenne",
  "statusList": [],
  "image": "images/img_17.jpg"
 },
 {
  "id": 34,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "B4-IN2642\n(Fakra D) - 5 m",
  "hersteller": "",
  "materialnummer": "10295861",
  "materialschluessel": "001-210204",
  "artikeltyp": "Z00245",
  "bestellnummer": "BZ0039",
  "typbezeichnung": "B4-IN2642",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_17.jpg"
 },
 {
  "id": 35,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "B4-IN2642\n(Fakra D) - 10 m",
  "hersteller": "",
  "materialnummer": "10295862",
  "materialschluessel": "001-210202",
  "artikeltyp": "Z00246",
  "bestellnummer": "BZ0041",
  "typbezeichnung": "B4-IN2642",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_17.jpg"
 },
 {
  "id": 36,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "B4-IN2642\n(SMA) - 2,5 m",
  "hersteller": "",
  "materialnummer": "10298803",
  "materialschluessel": "001-210212",
  "artikeltyp": "Z00398",
  "bestellnummer": "",
  "typbezeichnung": "B4-IN2642",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_17.jpg"
 },
 {
  "id": 37,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "B4-IN2642\n(SMA) - 5 m",
  "hersteller": "",
  "materialnummer": "10298804",
  "materialschluessel": "001-210213",
  "artikeltyp": "Z00399",
  "bestellnummer": "",
  "typbezeichnung": "B4-IN2642",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_17.jpg"
 },
 {
  "id": 38,
  "category": "Antennen - LTE-Stationsantennen - Fakra und SMA",
  "name": "B4-IN2642\n(SMA) - 10 m",
  "hersteller": "",
  "materialnummer": "10298805",
  "materialschluessel": "001-210214",
  "artikeltyp": "Z00400",
  "bestellnummer": "",
  "typbezeichnung": "B4-IN2642",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_17.jpg"
 },
 {
  "id": 39,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (Fakra) - 3 m",
  "hersteller": "A-Antennas",
  "materialnummer": "10292193",
  "materialschluessel": "001-210100",
  "artikeltyp": "Z00335",
  "bestellnummer": "BZ0043",
  "typbezeichnung": "Fakra CFD 195",
  "beschreibung": "Zur Verlängerung von Fakra und SMA",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": "images/img_18.jpg"
 },
 {
  "id": 40,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (Fakra) - 5 m",
  "hersteller": "",
  "materialnummer": "10295926",
  "materialschluessel": "001-210101",
  "artikeltyp": "Z00311",
  "bestellnummer": "BZ0044",
  "typbezeichnung": "Fakra CFD 195",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": "images/img_18.jpg"
 },
 {
  "id": 41,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (SMA) - 3 m",
  "hersteller": "",
  "materialnummer": "10298806",
  "materialschluessel": "001-210102",
  "artikeltyp": "Z00385",
  "bestellnummer": "",
  "typbezeichnung": "SMA CFD 195",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_18.jpg"
 },
 {
  "id": 42,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (SMA) - 5 m",
  "hersteller": "",
  "materialnummer": "10298807",
  "materialschluessel": "001-210103",
  "artikeltyp": "Z00387",
  "bestellnummer": "",
  "typbezeichnung": "SMA CFD 195",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_18.jpg"
 },
 {
  "id": 43,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (Fakra) - 3 m",
  "hersteller": "Panorama Antennas",
  "materialnummer": "10292193",
  "materialschluessel": "001-210100",
  "artikeltyp": "Z00305",
  "bestellnummer": "BZ0043",
  "typbezeichnung": "C2-IN2644-3",
  "beschreibung": "Zur Verlängerung von Fakra und SMA",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": "images/img_19.jpg"
 },
 {
  "id": 44,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (Fakra) - 5 m",
  "hersteller": "",
  "materialnummer": "10295926",
  "materialschluessel": "001-210101",
  "artikeltyp": "Z00312",
  "bestellnummer": "",
  "typbezeichnung": "C2-IN2644-5",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": "images/img_19.jpg"
 },
 {
  "id": 45,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (SMA) - 3 m",
  "hersteller": "",
  "materialnummer": "10298806",
  "materialschluessel": "001-210102",
  "artikeltyp": "Z00386",
  "bestellnummer": "",
  "typbezeichnung": "tbd.",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_19.jpg"
 },
 {
  "id": 46,
  "category": "Antennen Verlängerungen – Fakra und SMA",
  "name": "LTE Premium Antennen Verlängerungskabel - (SMA) - 5 m",
  "hersteller": "",
  "materialnummer": "10298807",
  "materialschluessel": "001-210103",
  "artikeltyp": "Z00388",
  "bestellnummer": "",
  "typbezeichnung": "tbd.",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_19.jpg"
 },
 {
  "id": 47,
  "category": "Antennenadapter",
  "name": "Antennenadapter (1)  Fakra(m) auf SMA(m)",
  "hersteller": "A-Antennas",
  "materialnummer": "10298796",
  "materialschluessel": "001-013005",
  "artikeltyp": "Z00361",
  "bestellnummer": "",
  "typbezeichnung": "Cable Adapter AA100 10cm Fakra D(m) Str./SMA(m) Str.\n31X-X001-BH-01",
  "beschreibung": "Verschiedene Adapter für Sonderfälle, unter anderem für die neue SMA-Premiumantenne",
  "statusList": [],
  "image": "images/img_20.jpg"
 },
 {
  "id": 48,
  "category": "Antennenadapter",
  "name": "Antennenadapter (2)  Fakra(f) auf FME(m)",
  "hersteller": "",
  "materialnummer": "10298797",
  "materialschluessel": "001-013006",
  "artikeltyp": "Z00363",
  "bestellnummer": "",
  "typbezeichnung": "Cable Adapter AA100 10cm Fakra D(f) RA/FME(m) Str.\n31X-X001-BE-01",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_21.jpg"
 },
 {
  "id": 49,
  "category": "Antennenadapter",
  "name": "Antennenadapter (3)  Fakra(m) auf MCX(m)",
  "hersteller": "",
  "materialnummer": "10298798",
  "materialschluessel": "001-013007",
  "artikeltyp": "Z00365",
  "bestellnummer": "",
  "typbezeichnung": "Cable Adapter AA100 10cm\nFakra D(m) Str./MCX(m) RA Grey\n31X-X001-BE-01",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_22.jpg"
 },
 {
  "id": 50,
  "category": "Antennenadapter",
  "name": "Antennenadapter (4)  FME(m) auf SMA(m)",
  "hersteller": "",
  "materialnummer": "10298799",
  "materialschluessel": "001-013008",
  "artikeltyp": "Z00367",
  "bestellnummer": "",
  "typbezeichnung": "Cable Adapter AA100 15cm FME(m)/SMA(m) Str.\n31X-X001-BJ-01",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_23.jpg"
 },
 {
  "id": 51,
  "category": "Antennenadapter",
  "name": "Antennenadapter (5)  Fakra(m) auf FME(f)",
  "hersteller": "",
  "materialnummer": "10298800",
  "materialschluessel": "001-013009",
  "artikeltyp": "Z00369",
  "bestellnummer": "",
  "typbezeichnung": "kein Etikett/ keine Leitung\n25X-X000-CJ-01",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_24.jpg"
 },
 {
  "id": 52,
  "category": "Antennenadapter",
  "name": "Antennenadapter (6)  SMA(f) auf Fakra(f)",
  "hersteller": "",
  "materialnummer": "10298801",
  "materialschluessel": "001-013010",
  "artikeltyp": "Z00371",
  "bestellnummer": "",
  "typbezeichnung": "Cable Adapter AA100 10cm SMA(f) Str./Fakra D(f) RA Grey\n31X-X001-BP-10",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_25.jpg"
 },
 {
  "id": 53,
  "category": "Antennenadapter",
  "name": "Antennenadapter (1)  Fakra(m) auf SMA(m)",
  "hersteller": "Panorama Antennas",
  "materialnummer": "10298796",
  "materialschluessel": "001-013005",
  "artikeltyp": "Z00362",
  "bestellnummer": "",
  "typbezeichnung": "RG174 FAKRA D PLUG TO SMA \nPLUG",
  "beschreibung": "Verschiedene Adapter für Sonderfälle, unter anderem für die neue SMA-Premiumantenne",
  "statusList": [],
  "image": "images/img_26.jpg"
 },
 {
  "id": 54,
  "category": "Antennenadapter",
  "name": "Antennenadapter (2)  Fakra(f) auf FME(m)",
  "hersteller": "",
  "materialnummer": "10298797",
  "materialschluessel": "001-013006",
  "artikeltyp": "Z00364",
  "bestellnummer": "",
  "typbezeichnung": "FME(m) TO R/A FAKRA D JACK RG174",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_27.jpg"
 },
 {
  "id": 55,
  "category": "Antennenadapter",
  "name": "Antennenadapter (3)  Fakra(m) auf MCX(m)",
  "hersteller": "",
  "materialnummer": "10298798",
  "materialschluessel": "001-013007",
  "artikeltyp": "Z00366",
  "bestellnummer": "",
  "typbezeichnung": "FR RG174 FAKRA D PLUG TO R/A \nMCX PLUG",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_28.jpg"
 },
 {
  "id": 56,
  "category": "Antennenadapter",
  "name": "Antennenadapter (4)  FME(m) auf SMA(m)",
  "hersteller": "",
  "materialnummer": "10298799",
  "materialschluessel": "001-013008",
  "artikeltyp": "Z00368",
  "bestellnummer": "",
  "typbezeichnung": "FME(m) - SMA(m) RG174 COAX CABLE",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_29.jpg"
 },
 {
  "id": 57,
  "category": "Antennenadapter",
  "name": "Antennenadapter (5)  Fakra(m) auf FME(f)",
  "hersteller": "",
  "materialnummer": "10298800",
  "materialschluessel": "001-013009",
  "artikeltyp": "Z00370",
  "bestellnummer": "",
  "typbezeichnung": "FME(f)-FAKRA D(m) ADAPTOR",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_30.jpg"
 },
 {
  "id": 58,
  "category": "Antennenadapter",
  "name": "Antennenadapter (6)  SMA(f) auf Fakra(f)",
  "hersteller": "",
  "materialnummer": "10298801",
  "materialschluessel": "001-013010",
  "artikeltyp": "Z00372",
  "bestellnummer": "",
  "typbezeichnung": "",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 59,
  "category": "Zusatzmaterial für klassische Zählertechnik",
  "name": "Leerfeldabdeckung klein - PZV1N",
  "hersteller": "ABN",
  "materialnummer": "10296957",
  "materialschluessel": "001-216001",
  "artikeltyp": "Z00252",
  "bestellnummer": "",
  "typbezeichnung": "PZV1N",
  "beschreibung": "Wurde durch\nZ00250 abgelöst!",
  "statusList": [],
  "image": "images/img_31.jpg"
 },
 {
  "id": 60,
  "category": "Zusatzmaterial für klassische Zählertechnik",
  "name": "Zählerfeldsperrverschluss - T95N (Zählerleerfeldabdeckung - klein)",
  "hersteller": "Hager",
  "materialnummer": "10296957",
  "materialschluessel": "001-216001",
  "artikeltyp": "Z00250",
  "bestellnummer": "",
  "typbezeichnung": "T95N",
  "beschreibung": "Inklusive Isoliertüllen",
  "statusList": [
   "lager-westnetz"
  ],
  "image": "images/img_32.jpg"
 },
 {
  "id": 61,
  "category": "Zusatzmaterial für klassische Zählertechnik",
  "name": "Zählerfeldsperrverschluss - T95L (Zählerleerfeldabdeckung - groß)",
  "hersteller": "",
  "materialnummer": "10297069",
  "materialschluessel": "001-216002",
  "artikeltyp": "Z00251",
  "bestellnummer": "",
  "typbezeichnung": "T95L",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz"
  ],
  "image": "images/img_33.jpg"
 },
 {
  "id": 62,
  "category": "Zusatzmaterial für klassische Zählertechnik",
  "name": "Zählerfeldsperrverschluss - T95E (Plombierschrauben)",
  "hersteller": "",
  "materialnummer": "10300702",
  "materialschluessel": "001-014002",
  "artikeltyp": "Z00279",
  "bestellnummer": "",
  "typbezeichnung": "T95E",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_34.jpg"
 },
 {
  "id": 63,
  "category": "Zusatzmaterial für klassische Zählertechnik",
  "name": "Zählerfeldsperrverschluss - T95A (Abreissschrauben)",
  "hersteller": "",
  "materialnummer": "10297269",
  "materialschluessel": "001-014003",
  "artikeltyp": "Z00280",
  "bestellnummer": "",
  "typbezeichnung": "T95A",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz"
  ],
  "image": "images/img_35.jpg"
 },
 {
  "id": 64,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Klemmendeckel - BZ - lang",
  "hersteller": "Landis+Gyr",
  "materialnummer": "10296652",
  "materialschluessel": "001-215025",
  "artikeltyp": "Z00404",
  "bestellnummer": "",
  "typbezeichnung": "P000394460 / Klemmendeckel FNN-BZ 80mm (S3) - noch ohne Ausstanzung",
  "beschreibung": "Klemmendeckel Basiszähler, passend für alle beschaffbaren Basiszähler",
  "statusList": [],
  "image": null
 },
 {
  "id": 65,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Klemmendeckel - BZ - Standard",
  "hersteller": "",
  "materialnummer": "10296637",
  "materialschluessel": "001-215026",
  "artikeltyp": "Z00406",
  "bestellnummer": "",
  "typbezeichnung": "P000414370 / Klemmendeckel FNN-BZ 60mm (S3) mit Aussparung",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 66,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Klemmendeckel - BZ - lang",
  "hersteller": "EFR",
  "materialnummer": "10296652",
  "materialschluessel": "001-215025",
  "artikeltyp": "Z00403",
  "bestellnummer": "",
  "typbezeichnung": "Klemmendeckel SGM-D4 lang",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 67,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Klemmendeckel - BZ - Standard",
  "hersteller": "",
  "materialnummer": "10296637",
  "materialschluessel": "001-215026",
  "artikeltyp": "Z00405",
  "bestellnummer": "",
  "typbezeichnung": "Klemmendeckel SGM-D4 standard",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 68,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Klemmendeckel - mME - lang",
  "hersteller": "",
  "materialnummer": "10300938",
  "materialschluessel": "001-215027",
  "artikeltyp": "Z00407",
  "bestellnummer": "",
  "typbezeichnung": "Klemmendeckel SGM-C8 lang",
  "beschreibung": "mME",
  "statusList": [],
  "image": null
 },
 {
  "id": 69,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Spezialklemmendeckel - BZ - Huckepack",
  "hersteller": "Landis+Gyr",
  "materialnummer": "10296656",
  "materialschluessel": "001-215009",
  "artikeltyp": "Z00409",
  "bestellnummer": "",
  "typbezeichnung": "P000386530 / Zähler-Klemmendeckeladapter E320 S3 (80mm)",
  "beschreibung": "Huckepackdeckel Basiszähler",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 70,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Spezialklemmendeckel - BZ - Huckepack",
  "hersteller": "EFR",
  "materialnummer": "10296656",
  "materialschluessel": "001-215009",
  "artikeltyp": "Z00408",
  "bestellnummer": "",
  "typbezeichnung": "",
  "beschreibung": "",
  "statusList": [],
  "image": null
 },
 {
  "id": 71,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Spezialklemmendeckel - mME - Huckepack mit Sicherung",
  "hersteller": "",
  "materialnummer": "10295225",
  "materialschluessel": "001-215002",
  "artikeltyp": "Z00333",
  "bestellnummer": "",
  "typbezeichnung": "Klemmendeckel Huckepack mit Sicherung, SGMZC0000000001",
  "beschreibung": "Huckepackdeckel mME",
  "statusList": [],
  "image": null
 },
 {
  "id": 72,
  "category": "Klemmen- und Huckepackdeckel (BZ und mME)",
  "name": "Spezialklemmendeckel - mME - Huckepack ohne Sicherung",
  "hersteller": "",
  "materialnummer": "10295091",
  "materialschluessel": "001-215001",
  "artikeltyp": "Z00319",
  "bestellnummer": "",
  "typbezeichnung": "Klemmendeckel Huckepack ohne Sicherung, SGMZC0000000004",
  "beschreibung": "",
  "statusList": [
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 73,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ - Ausstanzung (2x4TE)",
  "hersteller": "EFR",
  "materialnummer": "10296655",
  "materialschluessel": "001-215017",
  "artikeltyp": "Z00352",
  "bestellnummer": "BZ0026",
  "typbezeichnung": "Modulfachdeckel 4 TE links und rechts , SGMZDX0000002307",
  "beschreibung": "Modulfachdeckel Basiszähler, passend für alle beschaffbaren Basiszähler",
  "statusList": [
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 74,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ - Ausstanzung (4TE Links)",
  "hersteller": "",
  "materialnummer": "10292233",
  "materialschluessel": "001-215015",
  "artikeltyp": "Z00351",
  "bestellnummer": "BZ0025",
  "typbezeichnung": "Modulfachdeckel 4 TE links Ausstanzung SGMZDX0000002301",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 75,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ - Ausstanzung (5TE Links)",
  "hersteller": "",
  "materialnummer": "10300939",
  "materialschluessel": "001-215020",
  "artikeltyp": "Z00353",
  "bestellnummer": "BZ0053",
  "typbezeichnung": "Modulfachdeckel 5 TE links Ausstanzung, SGMZDX0000002303",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz"
  ],
  "image": null
 },
 {
  "id": 76,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ - geschlossen",
  "hersteller": "",
  "materialnummer": "10296654",
  "materialschluessel": "001-215014",
  "artikeltyp": "Z00350",
  "bestellnummer": "BZ0021",
  "typbezeichnung": "Modulfachdeckel ohne Ausstanzung SGMZDX0000002305",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 77,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ - Ausstanzung (4TE Links)",
  "hersteller": "Landis-Gyr",
  "materialnummer": "10292233",
  "materialschluessel": "001-215015",
  "artikeltyp": "Z00410",
  "bestellnummer": "BZ0025",
  "typbezeichnung": "P000395000 / Moduldeckel FNN-BZ mit Öffnung linksbündig",
  "beschreibung": "Modulfachdeckel Basiszähler, passend für alle beschaffbaren Basiszähler",
  "statusList": [],
  "image": null
 },
 {
  "id": 78,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ - geschlossen",
  "hersteller": "",
  "materialnummer": "10296654",
  "materialschluessel": "001-215014",
  "artikeltyp": "Z00411",
  "bestellnummer": "BZ0021",
  "typbezeichnung": "P000375830 / Moduldeckel FNN-BZ",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz"
  ],
  "image": null
 },
 {
  "id": 79,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ WZ - Ausstanzung (4TE Links)",
  "hersteller": "",
  "materialnummer": "10296751",
  "materialschluessel": "001-215019",
  "artikeltyp": "Z00345",
  "bestellnummer": "BZ0055",
  "typbezeichnung": "P000412450 / Moduldeckel FNN-BZ mit Öff(linksbdg)+Wschild",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 80,
  "category": "Modulfachdeckel",
  "name": "Modulfachdeckel - BZ WZ - geschlossen",
  "hersteller": "",
  "materialnummer": "10296752",
  "materialschluessel": "001-215018",
  "artikeltyp": "Z00344",
  "bestellnummer": "BZ0054",
  "typbezeichnung": "P000412430 / Moduldeckel FNN-BZ mit Wandlerschild",
  "beschreibung": "",
  "statusList": [
   "lager-westnetz",
   "lager-egs"
  ],
  "image": null
 },
 {
  "id": 81,
  "category": "Antennen - LTE-Antennen 450 MHz",
  "name": "LTE 450 Premium Antenne - Pifa P-450 - 3m - nur Feldtest 450 MHz",
  "hersteller": "A-Antennas",
  "materialnummer": "10295918",
  "materialschluessel": "001-210052",
  "artikeltyp": "Z00339",
  "bestellnummer": "",
  "typbezeichnung": "60G-A030-AK-01",
  "beschreibung": "Projektantennen 2023",
  "statusList": [],
  "image": "images/img_36.png"
 },
 {
  "id": 82,
  "category": "Antennen - LTE-Antennen 450 MHz",
  "name": "LTE 450 Standard Antenne - LPW-460-2RFDJ - 2m - nur Feldtest 450 MHz",
  "hersteller": "Panorama-Antennas",
  "materialnummer": "10295943",
  "materialschluessel": "001-210051",
  "artikeltyp": "Z00340",
  "bestellnummer": "",
  "typbezeichnung": "LPW-460-2RFDJ",
  "beschreibung": "",
  "statusList": [],
  "image": "images/img_37.png"
 }
];
